### PR TITLE
fix: 🐛 try to fix goroutines exportEventsTimeout

### PR DESCRIPTION
**Pull request by wind2008hxy**
**What type of PR is this?**
**PR类型是什么？**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
>  bug

**What this PR does / why we need it**:
**这个PR解决了什么问题**:
try to fix goroutines exportEventsTimeout
尝试修复travis ci 测试过程报错

image

**Which issue(s) this PR fixes**:
**PR相关联issue**:

Fixes #

**Does this PR introduce a breaking change?**:
**PR带来的破坏性变更**:

None
```docs

```

**Test/Final result**:
**测试/最终运行结果**:

### CODE REVIEW

**Comment by wind2008hxy** [comment]
image

**Comment by wind2008hxy** [comment]
https://github.com/AliyunContainerService/kube-eventer/blob/548ea0a3a748499e424da1af514f1fe49ddc1fa6/sinks/manager_test.go#L35
&batch实际是同一个内存地址，多个goroutines尝试读取的时候，实际会是多个goroutines顺序读取，猜测是这里导致超时。

**Comment by wind2008hxy** [comment]
rebase to one commit?

**Comment by ringtail** [comment]
> rebase to one commit?

Yes

**Comment by wind2008hxy** [comment]
> need `rebase`

rebase

**Pull request merged**
