### PR TITLE
add wechat sink

### PR DESCRIPTION
**Pull request by zalmanzhao**
使用方式
````
--sink=wechat:https://wechat?corp_id=xxxxx&corp_secret=xxxxxxx&agent_id=1000012&to_user=<user>&label=<label>&level=Normal
````
to_user使用逗号分隔需要通知的用户，如果为空则通知所有当前组下的所有用户

### CODE REVIEW

**Comment by ringtail** [comment]
#22

**Comment by ringtail** [comment]
@zalmanzhao Could you add a doc in docs/en/wechat.md

**Comment by ringtail** [comment]
Pls `make sanitize` in local

**Comment by zalmanzhao** [comment]
ok, do it when I'm free.

**Comment by zalmanzhao** [comment]
done

**Comment by ringtail** [comment]
@zalmanzhao Pls solve the review advices above

**Comment by ringtail** [comment]
@zalmanzhao There are still some fragments needed to be fixed. Pls see the comment above.

**Comment by ringtail** [comment]
@zalmanzhao /stale disabled

**Comment by ringtail** [comment]
I'll help you to fix the comment later.

**Pull request merged**
